apiVersion: v1
kind: Secret 
metadata:
  name: crud-app-backend-secret
  namespace: crud-app-backend
type: Opaque
data: 
  DB_NAME: ZW1wbG95ZWU=
  DB_USERNAME: bWV0cm9wb2w=
  DB_PASSWORD: MjAwMDIwMDI=
